// Base generated by AI - Claude Sonnet 5 2026
/* ==========================================================================
   LIBRARY DATA
   ==========================================================================
   This is the only file you should need to edit to add your own music.

   Structure:
   LIBRARY = [
     {
       artist: "Artist name",
       albums: [
         {
           title: "Album name",
           year: "2024",           // optional, shown in the album header
           songs: [
             {
               title: "Song title",
               duration: "3:24",   // optional fallback shown until the
                                    // audio file's real length loads
               src: "//song_file"  // <-- replace with the real path/URL
                                    //     to the audio file, e.g.
                                    //     "songs/artist/album/track.mp3"
             },
             ...
           ]
         },
         ...
       ]
     },
     ...
   ]

   Every song currently points at the placeholder "//song_file" — swap
   each one out for the actual audio file once you have it. Nothing else
   in the app needs to change; the player reads directly from this file.
   ========================================================================== */

const LIBRARY = [
  {
    artist: "Interval 11",
    albums: [
      { // Album 1 Beyond Knowing
        title: "Beyond Knowing",
        cover: 'library/Interval 11/Beyond Knowing/Beyond Knowing.png',
        year: "2024",
        songs: [
          { title: "In Hearse", duration: "2:03", src: "library/Interval 11/Beyond Knowing/In_Hearse.mp3" },
          { title: "Treasure for Another", duration: "3:56", src: "library/Interval 11/Beyond Knowing/Treasure_for_Another.mp3" },
          { title: "The Shallows", duration: "2:58", src: "library/Interval 11/Beyond Knowing/The Shallows.mp3" },
          { title: "Natural Order", duration: "6:23", src: "library/Interval 11/Beyond Knowing/Natural Order.mp3" },
          { title: "Three Flames", duration: "5:34", src: "library/Interval 11/Beyond Knowing/Three_Flames.mp3"},
          { title: "Say the Reason", duration: "4:22", src: "library/Interval 11/Beyond Knowing/Say_the_Reason.mp3" },
          { title: "Idyllic", duration: "4:18", src: "library/Interval 11/Beyond Knowing/Idyllic.mp3" },
          { title: "Who Knew, I'm Fine", duration: "2:41", src: "library/Interval 11/Beyond Knowing/Who Knew I'm Fine.mp3" },
          { title: "Out of Sight", duration: "5:30", src: "library/Interval 11/Beyond Knowing/Out_of_Sight.mp3" },
          { title: "Drifting Planets", duration: "6:39", src: "library/Interval 11/Beyond Knowing/Drifting_Planets.mp3" },
          { title: "Lost in Shadows", duration: "3:12", src: "library/Interval 11/Beyond Knowing/Lost in Shadows.mp3" },
          { title: "Dying to Wait for You", duration: "3:59", src: "library/Interval 11/Beyond Knowing/Dying_to_Wait_for_You.mp3" }
        ]
      }
    ] // End Interval 11 albums (array of objects)
  },
  {
    artist: "Avalanche Paths",
    albums: [
      {
        title: "Scioto Darby",
        cover: 'library/Avalanche Paths/Scioto Darby EP/APSD_1.jpg',
        year: "2024",
        songs: [
          { title: "Movie Day", duration: "3:43", src: "library/Avalanche Paths/Scioto Darby EP/Movie Day.wav" },
          { title: "Blotter", duration: "4:40", src: "library/Avalanche Paths/Scioto Darby EP/Blotter.wav" },
          { title: "Codename Z", duration: "2:35", src: "library/Avalanche Paths/Scioto Darby EP/Codename Z.wav" },
          { title: "Warm October", duration: "5:01", src: "library/Avalanche Paths/Scioto Darby EP/Warm October.wav" }
        ]
      },
      {
        title: '2026',
        cover: '',
        year: '2026',
        songs: [
          { title: 'Explode', duration: '3:09', src: 'library/Avalanche Paths/2026/Explode_2.mp3'},
          { title: 'Gauntlet', duration: '7:47', src: 'library/Avalanche Paths/2026/Gauntlet_2026_01.mp3'},
          { title: 'Advent', duration: '4:33', src: 'library/Avalanche Paths/2026/advent_rough.mp3'},
          { title: 'eyeswideshut', duration: '4:50', src: 'library/Avalanche Paths/2026/eyeswideshut_RAW.mp3'},
          { title: 'Blase', duration: '4:50', src: 'library/Avalanche Paths/2026/Blase_Rough9-23-26.mp3'}

        ]
      },
      {
        title: "Fata Morgana",
        cover: '',
        year: '2026',
        songs: [
          { title: 'Fata Morgana', duration: '3:36', src: 'library/Avalanche Paths/Fata Morgana/Fata Morgana_Raw_8-8-26.mp3'},
          { title: 'Incline', duration: '4:28', src: 'library/Avalanche Paths/Fata Morgana/Incline_8-8-26.mp3'},
          { title: 'Morello Cherry', duration: '2:55', src: 'library/Avalanche Paths/Fata Morgana/Morello Cherry_8-8-26.mp3'},
          { title: 'Snowdrift', duration: '3:33', src: 'library/Avalanche Paths/Fata Morgana/Snowdrift_8-8-26.mp3'},
          { title: 'Swords at the Lake', duration: '3:03', src: 'library/Avalanche Paths/Fata Morgana/Swords_8-8-26.mp3'},
          { title: 'Traffic', duration: '4:25', src: 'library/Avalanche Paths/Fata Morgana/Traffic_RAW MIX.mp3'},
          { title: 'Trails', duration: '5:33', src: 'library/Avalanche Paths/Fata Morgana/Trails_8-8-26.mp3'},
          { title: 'Winter\'s Crown', duration: '3:39', src: 'library/Avalanche Paths/Fata Morgana/Winters Crown_8-8-26.mp3'}
        ]
      }
    ] // End Avalanche Paths Albums
  },
  {
    artist: 'Time-Like Interval',
    albums: [
      {
        title: 'The Final Page',
        cover: 'library/Time-Like Interval/The Final Page/Lunarium.jpg',
        year: '2017',
        songs: [
          { title: 'Clothespin', duration: '5:44', src: 'library/Time-Like Interval/The Final Page/Clothespin.mp3'},
          { title: 'Overpass', duration: '2:37', src: 'library/Time-Like Interval/The Final Page/Overpass.mp3'},
          { title: 'Buzzed Dark Year', duration: '4:47', src: 'library/Time-Like Interval/The Final Page/Buzzed Dark Year.mp3'},
          { title: 'Transition', duration: '0:51', src: 'library/Time-Like Interval/The Final Page/Transition.mp3'},
          { title: 'Into The Mist', duration: '4:15', src: 'library/Time-Like Interval/The Final Page/Into The Mist.mp3'},
          { title: 'Half-truth', duration: '8:03', src: 'library/Time-Like Interval/The Final Page/Half-truth.mp3'},
          { title: 'Azimuth', duration: '2:03', src: 'library/Time-Like Interval/The Final Page/Azimuth.mp3'},
          { title: 'Heave Ho', duration: '3:40', src: 'library/Time-Like Interval/The Final Page/Heave Ho.mp3'},
          { title: 'Syrup', duration: '4:12', src: 'library/Time-Like Interval/The Final Page/Syrup.mp3'},
          { title: 'Time Lake', duration: '10:38', src: 'library/Time-Like Interval/The Final Page/Time Lake.mp3'},
          { title: 'Penk Flod', duration: '5:05', src: 'library/Time-Like Interval/The Final Page/Penk Flod.mp3'},
          { title: 'The Song to End on', duration: '4:54', src: 'library/Time-Like Interval/The Final Page/The Song to End on.mp3'}
        ]
      }
    ]
    
  }
];
