// Base generated by AI - Claude Sonnet 5 2026
/* ==========================================================================
   LIBRARY DATA
   ==========================================================================
   This is the only file you should need to edit to add your own music.

   Structure:
   LIBRARY = [
     {
       artist: "Artist name",
       albums: [
         {
           title: "Album name",
           year: "2024",           // optional, shown in the album header
           songs: [
             {
               title: "Song title",
               duration: "3:24",   // optional fallback shown until the
                                    // audio file's real length loads
               src: "//song_file"  // <-- replace with the real path/URL
                                    //     to the audio file, e.g.
                                    //     "songs/artist/album/track.mp3"
             },
             ...
           ]
         },
         ...
       ]
     },
     ...
   ]

   Every song currently points at the placeholder "//song_file" — swap
   each one out for the actual audio file once you have it. Nothing else
   in the app needs to change; the player reads directly from this file.
   ========================================================================== */

const LIBRARY = [
  {
    artist: "Interval 11",
    albums: [
      { // Album 1 Beyond Knowing
        title: "Beyond Knowing",
        cover: 'library/Interval 11/Beyond Knowing/Beyond Knowing.png',
        year: "2024",
        songs: [
          { title: "In Hearse", duration: "2:03", src: "library/Interval 11/Beyond Knowing/In_Hearse.mp3" },
          { title: "Treasure for Another", duration: "3:56", src: "library/Interval 11/Beyond Knowing/Treasure_for_Another.mp3" },
          { title: "The Shallows", duration: "2:58", src: "library/Interval 11/Beyond Knowing/The Shallows.mp3" },
          { title: "Natural Order", duration: "6:23", src: "library/Interval 11/Beyond Knowing/Natural Order.mp3" },
          { title: "Three Flames", duration: "5:34", src: "library/Interval 11/Beyond Knowing/Three_Flames.mp3 "},
          { title: "Say the Reason", duration: "4:22", src: "library/Interval 11/Beyond Knowing/Say_the_Reason.mp3" },
          { title: "Idyllic", duration: "4:18", src: "library/Interval 11/Beyond Knowing/Idyllic.mp3" },
          { title: "Who Knew, I'm Fine", duration: "2:41", src: "library/Interval 11/Beyond Knowing/Who Knew I'm Fine.mp3" },
          { title: "Out of Sight", duration: "5:30", src: "library/Interval 11/Beyond Knowing/Out_of_Sight.mp3" },
          { title: "Drifting Planets", duration: "6:39", src: "library/Interval 11/Beyond Knowing/Drifting_Planets.mp3" },
          { title: "Lost in Shadows", duration: "3:12", src: "library/Interval 11/Beyond Knowing/Lost in Shadows.mp3" },
          { title: "Dying to Wait for You", duration: "3:59", src: "library/Interval 11/Beyond Knowing/Dying_to_Wait_for_You.mp3" }
        ]
      }
    ] // End Interval 11 albums (array of objects)
  },
  {
    artist: "Avalanche Paths",
    albums: [
      {
        title: "Scioto Darby",
        cover: 'library/Avalanche Paths/Scioto Darby EP/APSD_1.jpg',
        year: "2024",
        songs: [
          { title: "Movie Day", duration: "3:43", src: "library/Avalanche Paths/Scioto Darby EP/Movie Day.wav" },
          { title: "Blotter", duration: "4:40", src: "library/Avalanche Paths/Scioto Darby EP/Blotter.wav" },
          { title: "Codename Z", duration: "2:35", src: "library/Avalanche Paths/Scioto Darby EP/Codename Z.wav" },
          { title: "Warm October", duration: "5:01", src: "library/Avalanche Paths/Scioto Darby EP/Warm October.wav" }
        ]
      }
    ] // End Avalanche Paths Albums
  }
];
