// Base generated by AI - Claude Sonnet 5 2026
(function () {
  "use strict";

  /* ------------------------------------------------------------------
     Element references
     ------------------------------------------------------------------ */
  const libraryListEl = document.getElementById("libraryList");
  const searchInput   = document.getElementById("searchInput");

  const viewHeaderEl  = document.getElementById("viewHeader");
  const trackListEl   = document.getElementById("trackList");

  const audio         = document.getElementById("audio");

  const playBtn        = document.getElementById("playBtn");
  const prevBtn         = document.getElementById("prevBtn");
  const nextBtn         = document.getElementById("nextBtn");
  const playIcon       = document.getElementById("playIcon");
  const pauseIcon      = document.getElementById("pauseIcon");

  const seekEl         = document.getElementById("seek");
  const curTimeEl      = document.getElementById("curTime");
  const durTimeEl      = document.getElementById("durTime");
  const trackIndexEl   = document.getElementById("trackIndex");

  const volumeEl       = document.getElementById("volume");
  const muteBtn        = document.getElementById("muteBtn");
  const volIconOn      = document.getElementById("volIconOn");
  const volIconOff     = document.getElementById("volIconOff");

  const npArtEl        = document.getElementById("npArt");
  const npTitleEl      = document.getElementById("npTitle");
  const npSubEl        = document.getElementById("npSub");

  /* ------------------------------------------------------------------
     Palette used for generated album/artist art tiles.
     Picked deterministically from the album title so the same album
     always gets the same color.
     ------------------------------------------------------------------ */
  const ART_PALETTE = [
    "linear-gradient(155deg, #e8a33d, #a9622a)",
    "linear-gradient(155deg, #6fa3a0, #35595a)",
    "linear-gradient(155deg, #c96b5a, #7a3630)",
    "linear-gradient(155deg, #8a8fc9, #464a86)",
    "linear-gradient(155deg, #d9c26a, #8a6f24)",
    "linear-gradient(155deg, #7fa876, #3f6b3d)"
  ];

  function hashString(str) {
    let h = 0;
    for (let i = 0; i < str.length; i++) {
      h = (h << 5) - h + str.charCodeAt(i);
      h |= 0;
    }
    return Math.abs(h);
  }

  function artFor(text) {
    return ART_PALETTE[hashString(text) % ART_PALETTE.length];
  }

  /**
   * Fills `container` with the generated color-tile + initials, then
   * (if `coverSrc` is given) layers a real <img> on top. If the image
   * loads successfully the initials are hidden behind it; if it fails
   * to load, the <img> removes itself and the tile shows as normal.
   */
  function paintCover(container, labelText, coverSrc) {
    container.style.background = artFor(labelText);
    container.classList.remove("has-image");
    container.innerHTML = `<span class="cover-initials">${initials(labelText)}</span>`;

    if (!coverSrc) return;

    const img = document.createElement("img");
    img.className = "cover-img";
    img.alt = "";
    img.addEventListener("load", () => container.classList.add("has-image"));
    img.addEventListener("error", () => img.remove());
    img.src = coverSrc;
    container.appendChild(img);
  }

  function initials(text) {
    return text
      .split(/\s+/)
      .filter(Boolean)
      .slice(0, 2)
      .map(w => w[0].toUpperCase())
      .join("");
  }

  /* ------------------------------------------------------------------
     Player state
     ------------------------------------------------------------------ */
  const state = {
    artistIndex: null,   // index into LIBRARY of the open/selected artist
    albumIndex: null,    // index into LIBRARY[artistIndex].albums
    queue: [],           // the list of songs currently playable in order
    queueContext: null,  // { artist, album } the queue came from
    currentSongIndex: -1,
    isPlaying: false
  };

  /* ------------------------------------------------------------------
     Sidebar: render artists / albums
     ------------------------------------------------------------------ */
  function renderLibrary(filterText) {
    const filter = (filterText || "").trim().toLowerCase();
    libraryListEl.innerHTML = "";

    let anyVisible = false;

    LIBRARY.forEach((artistEntry, artistIdx) => {
      const artistMatches = artistEntry.artist.toLowerCase().includes(filter);

      const visibleAlbums = artistEntry.albums
        .map((album, albumIdx) => ({ album, albumIdx }))
        .filter(({ album }) => {
          if (!filter) return true;
          if (artistMatches) return true;
          if (album.title.toLowerCase().includes(filter)) return true;
          return album.songs.some(s => s.title.toLowerCase().includes(filter));
        });

      if (filter && visibleAlbums.length === 0) return;

      anyVisible = true;

      const group = document.createElement("div");
      group.className = "artist-group";
      const isOpen = filter
        ? true
        : state.artistIndex === artistIdx;
      if (isOpen) group.classList.add("is-open");

      const artistBtn = document.createElement("button");
      artistBtn.className = "artist-row";
      artistBtn.setAttribute("aria-expanded", isOpen ? "true" : "false");
      artistBtn.innerHTML = `
        <svg class="chevron" viewBox="0 0 24 24" width="12" height="12"><path d="M9 6l7 6-7 6" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round"/></svg>
        <span>${escapeHtml(artistEntry.artist)}</span>
      `;
      artistBtn.addEventListener("click", () => {
        state.artistIndex = state.artistIndex === artistIdx ? null : artistIdx;
        renderLibrary(searchInput.value);
      });

      const albumList = document.createElement("div");
      albumList.className = "album-list";

      visibleAlbums.forEach(({ album, albumIdx }) => {
        const albumBtn = document.createElement("button");
        albumBtn.className = "album-row";
        if (state.artistIndex === artistIdx && state.albumIndex === albumIdx) {
          albumBtn.classList.add("is-active");
        }
        albumBtn.textContent = album.title;
        albumBtn.addEventListener("click", () => {
          state.artistIndex = artistIdx;
          state.albumIndex = albumIdx;
          renderLibrary(searchInput.value);
          renderAlbumView(artistIdx, albumIdx);
        });
        albumList.appendChild(albumBtn);
      });

      group.appendChild(artistBtn);
      group.appendChild(albumList);
      libraryListEl.appendChild(group);
    });

    if (!anyVisible) {
      const empty = document.createElement("p");
      empty.className = "no-results";
      empty.textContent = "No matches. Try a different search.";
      libraryListEl.appendChild(empty);
    }
  }

  function escapeHtml(str) {
    const div = document.createElement("div");
    div.textContent = str;
    return div.innerHTML;
  }

  /* ------------------------------------------------------------------
     Main view: album header + track list
     ------------------------------------------------------------------ */
  function renderAlbumView(artistIdx, albumIdx) {
    const artistEntry = LIBRARY[artistIdx];
    const album = artistEntry.albums[albumIdx];

    viewHeaderEl.innerHTML = "";
    const header = document.createElement("div");
    header.style.display = "contents";

    const cover = document.createElement("div");
    cover.className = "album-cover";
    paintCover(cover, album.title, album.cover);

    const heading = document.createElement("div");
    heading.className = "album-heading";
    heading.innerHTML = `
      <p class="kicker">Album</p>
      <h2>${escapeHtml(album.title)}</h2>
      <p class="meta-line">${escapeHtml(artistEntry.artist)}<span class="dot">·</span>${album.songs.length} track${album.songs.length === 1 ? "" : "s"}${album.year ? `<span class="dot">·</span>${escapeHtml(album.year)}` : ""}</p>
    `;

    viewHeaderEl.appendChild(cover);
    viewHeaderEl.appendChild(heading);

    renderTrackList(artistIdx, albumIdx);
  }

  function renderTrackList(artistIdx, albumIdx) {
    const artistEntry = LIBRARY[artistIdx];
    const album = artistEntry.albums[albumIdx];

    trackListEl.innerHTML = "";

    album.songs.forEach((song, songIdx) => {
      const row = document.createElement("div");
      row.className = "track-row";

      const isCurrentQueue =
        state.queueContext &&
        state.queueContext.artist === artistIdx &&
        state.queueContext.album === albumIdx;
      const isActive = isCurrentQueue && state.currentSongIndex === songIdx;
      if (isActive) row.classList.add("is-active");

      row.innerHTML = `
        <span class="idx">
          <span class="num">${songIdx + 1}</span>
          <span class="play-glyph">${state.isPlaying && isActive ? playingGlyph() : pausedGlyph()}</span>
        </span>
        <span class="title-wrap">
          <span class="t-title">${escapeHtml(song.title)}</span>
          <span class="t-sub">${escapeHtml(artistEntry.artist)}</span>
        </span>
        <span class="t-duration mono">${escapeHtml(song.duration || "—:—")}</span>
      `;

      row.addEventListener("click", () => {
        playAlbumFrom(artistIdx, albumIdx, songIdx);
      });

      trackListEl.appendChild(row);
    });
  }

  function playingGlyph() {
    return `<svg viewBox="0 0 24 24" width="12" height="12"><rect x="6" y="5" width="4" height="14" fill="currentColor"/><rect x="14" y="5" width="4" height="14" fill="currentColor"/></svg>`;
  }
  function pausedGlyph() {
    return `<svg viewBox="0 0 24 24" width="12" height="12"><path d="M7 5v14l12-7z" fill="currentColor"/></svg>`;
  }

  /* ------------------------------------------------------------------
     Playback: building a queue from an album and controlling <audio>
     ------------------------------------------------------------------ */
  function playAlbumFrom(artistIdx, albumIdx, songIdx) {
    const artistEntry = LIBRARY[artistIdx];
    const album = artistEntry.albums[albumIdx];

    state.queue = album.songs.map(s => ({
      ...s,
      artist: artistEntry.artist,
      album: album.title,
      cover: album.cover
    }));
    state.queueContext = { artist: artistIdx, album: albumIdx };
    state.currentSongIndex = songIdx;

    loadAndPlayCurrent();
  }

  function loadAndPlayCurrent() {
    const song = state.queue[state.currentSongIndex];
    if (!song) return;

    audio.src = song.src;
    audio.currentTime = 0;
    audio.play().catch(() => {
      /* Autoplay may be blocked until the user interacts with the page;
         the transport still reflects the correct paused state. */
    });

    updateNowPlaying(song);
    updateTransportEnabled();
    updateTrackIndexReadout();

    if (state.queueContext) {
      renderTrackList(state.queueContext.artist, state.queueContext.album);
    }
  }

  function updateNowPlaying(song) {
    paintCover(npArtEl, song.album, song.cover);
    npTitleEl.textContent = song.title;
    npSubEl.textContent = `${song.artist} — ${song.album}`;
  }

  function updateTransportEnabled() {
    const hasQueue = state.queue.length > 0 && state.currentSongIndex >= 0;
    playBtn.disabled = !hasQueue;
    prevBtn.disabled = !hasQueue;
    nextBtn.disabled = !hasQueue;
    seekEl.disabled = !hasQueue;
  }

  function updateTrackIndexReadout() {
    if (state.queue.length === 0) {
      trackIndexEl.textContent = "— / —";
      return;
    }
    trackIndexEl.textContent = `${state.currentSongIndex + 1} / ${state.queue.length}`;
  }

  function setPlayingUI(isPlaying) {
    state.isPlaying = isPlaying;
    playIcon.style.display = isPlaying ? "none" : "block";
    pauseIcon.style.display = isPlaying ? "block" : "none";
    playBtn.setAttribute("aria-label", isPlaying ? "Pause" : "Play");
    if (state.queueContext) {
      renderTrackList(state.queueContext.artist, state.queueContext.album);
    }
  }

  function togglePlayPause() {
    if (state.currentSongIndex < 0) return;
    if (audio.paused) {
      audio.play().catch(() => {});
    } else {
      audio.pause();
    }
  }

  function goToOffset(offset) {
    if (state.queue.length === 0) return;
    const next = state.currentSongIndex + offset;
    if (next < 0 || next >= state.queue.length) return;
    state.currentSongIndex = next;
    loadAndPlayCurrent();
  }

  function handleTrackEnded() {
    // Autoplay to the next song when the current one finishes.
    if (state.currentSongIndex + 1 < state.queue.length) {
      goToOffset(1);
    } else {
      // End of album/queue: stop and reset the scrubber.
      setPlayingUI(false);
      seekEl.value = 0;
      curTimeEl.textContent = "0:00";
    }
  }

  /* ------------------------------------------------------------------
     Time formatting + scrubber sync
     ------------------------------------------------------------------ */
  function formatTime(seconds) {
    if (!isFinite(seconds) || seconds < 0) return "0:00";
    const m = Math.floor(seconds / 60);
    const s = Math.floor(seconds % 60);
    return `${m}:${String(s).padStart(2, "0")}`;
  }

  let isScrubbing = false;

  audio.addEventListener("loadedmetadata", () => {
    durTimeEl.textContent = formatTime(audio.duration);
  });

  audio.addEventListener("timeupdate", () => {
    if (isScrubbing) return;
    curTimeEl.textContent = formatTime(audio.currentTime);
    if (audio.duration) {
      seekEl.value = String((audio.currentTime / audio.duration) * 1000);
    }
  });

  audio.addEventListener("play", () => setPlayingUI(true));
  audio.addEventListener("pause", () => setPlayingUI(false));
  audio.addEventListener("ended", handleTrackEnded);

  seekEl.addEventListener("input", () => {
    isScrubbing = true;
    if (audio.duration) {
      const t = (Number(seekEl.value) / 1000) * audio.duration;
      curTimeEl.textContent = formatTime(t);
    }
  });

  seekEl.addEventListener("change", () => {
    if (audio.duration) {
      audio.currentTime = (Number(seekEl.value) / 1000) * audio.duration;
    }
    isScrubbing = false;
  });

  /* ------------------------------------------------------------------
     Volume
     ------------------------------------------------------------------ */
  let lastVolume = 0.8;
  audio.volume = lastVolume;

  volumeEl.addEventListener("input", () => {
    const v = Number(volumeEl.value) / 100;
    audio.volume = v;
    audio.muted = v === 0;
    updateVolumeIcon();
  });

  muteBtn.addEventListener("click", () => {
    if (audio.muted || audio.volume === 0) {
      audio.muted = false;
      audio.volume = lastVolume || 0.8;
      volumeEl.value = String(Math.round(audio.volume * 100));
    } else {
      lastVolume = audio.volume;
      audio.muted = true;
    }
    updateVolumeIcon();
  });

  function updateVolumeIcon() {
    const silent = audio.muted || audio.volume === 0;
    volIconOn.style.display = silent ? "none" : "block";
    volIconOff.style.display = silent ? "block" : "none";
  }

  /* ------------------------------------------------------------------
     Transport button wiring
     ------------------------------------------------------------------ */
  playBtn.addEventListener("click", togglePlayPause);
  prevBtn.addEventListener("click", () => goToOffset(-1));
  nextBtn.addEventListener("click", () => goToOffset(1));

  /* ------------------------------------------------------------------
     Search
     ------------------------------------------------------------------ */
  searchInput.addEventListener("input", () => {
    renderLibrary(searchInput.value);
  });

  /* ------------------------------------------------------------------
     Init
     ------------------------------------------------------------------ */
  renderLibrary("");
  updateTransportEnabled();
  updateTrackIndexReadout();
  updateVolumeIcon();
})();